version: "3"

services:
  app:
    image: nicolkill/enconta_test:latest
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
    volumes:
      - .:/app

networks:
  proxy:
    external: true
